# Generated by Django 3.2.9 on 2021-11-14 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_navigated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('plate', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('navigation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.navigation')),
            ],
        ),
        migrations.AddField(
            model_name='navigation',
            name='vehicle_plate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.vehicle'),
        ),
    ]
